GraphEmbedding_Core:
  hidden_dim: 128
  graph_vector_dim: 128
  n_layer: 4
  dropout: 0.0

GraphEmbedding_Block:
  hidden_dim: 128
  graph_vector_dim: 128
  n_layer: 4
  dropout: 0.0

TerminationPredictionModel:
  core_graph_vector_dim: ${GraphEmbedding_Core.graph_vector_dim}
  hidden_dim: 128
  dropout: 0.0

BlockSelectionModel:
  core_graph_vector_dim: ${GraphEmbedding_Core.graph_vector_dim}
  block_graph_vector_dim: ${GraphEmbedding_Block.graph_vector_dim}
  hidden_dim: 128
  dropout: 0.0

AtomSelectionModel:
  core_graph_vector_dim: ${GraphEmbedding_Core.graph_vector_dim}
  block_graph_vector_dim: ${GraphEmbedding_Block.graph_vector_dim}
  hidden_dim: 128
  n_layer: 4
  dropout: 0.0
